### ISSUE TITLE
Adalons Blood vs Tangled Isle

### ISSUE THREAD

**Issue by 11jo** [Gitjas/Adalons_Blood#2]
A french player [report an issue](https://www.baldursgateworld.fr/viewtopic.php?p=518199#p518199) with Adalon quest.

It seem that the mod Tangled Isle from Lava provide another way to got MISC8H.itm and allow the player to resolve the quest even before going to underdark. (You can take a look at RIBALD.D inside Tangled Isle dialogues folder )

The issue in this case is that none of the triggers return true for the final Adalon talk in UDSILVER.DLG, when you give her the eggs.

```
UDSILVER.DLG // Block 45
IF ~~ THEN BEGIN 45
  SAY #51638
  IF ~  OR(3)
Global("C#SilberdrachenblutQuestTod","GLOBAL",1)
Global("TalkedToTanally1","GLOBAL",0)
Dead("TANALLY1")
~ THEN GOTO 46
  IF ~  Global("C#SilberdrachenblutQuestTod","GLOBAL",0)
Global("C#SB_Silberdrachenblut","GLOBAL",0)
!Dead("TANALLY1")
Global("TalkedToTanally1","GLOBAL",1)
~ THEN REPLY #326510 GOTO 61
  IF ~  Global("C#SilberdrachenblutQuestTod","GLOBAL",0)
Global("C#SB_Silberdrachenblut","GLOBAL",0)
Global("TalkedToTanally1","GLOBAL",1)
!Dead("TANALLY1")
~ THEN REPLY #326511 DO ~SetGlobal("C#SB_DrowCityHostile","GLOBAL",1)
~ GOTO 46
  IF ~  Global("C#SilberdrachenblutQuestTod","GLOBAL",0)
Global("C#SB_Silberdrachenblut","GLOBAL",1)
Global("TalkedToTanally1","GLOBAL",1)
!Dead("TANALLY1")
~ THEN GOTO 80
END
```

Maybe adding

`OR(4)`
`Global("TalkedToTanally1","GLOBAL",2)`  (This variable is set when Fael have the blood MISC8H.itm and start to craft the armor)

in [the first block, here](https://github.com/Gitjas/Adalons_Blood/blob/30406b1abdb989e918832a535c85b2161753d7b8/c%23sb_silber/dialoge/silberdrachenblut.d#L3) :

```
IF ~~ THEN BEGIN 45
  IF ~  OR(4)
Global("C#SilberdrachenblutQuestTod","GLOBAL",1)
Global("TalkedToTanally1","GLOBAL",0)
Dead("TANALLY1")
Global("TalkedToTanally1","GLOBAL",2)
~ THEN GOTO 46
```

Should resolve the incompatibility.

**Comment by Gitjas** [comment]
This sounds like a good idea. Thank you!

**Comment by Gitjas** [comment]
I'll go with
`~OR(3) Global("C#SilberdrachenblutQuestTod","GLOBAL",1)
!Global("TalkedToTanally1","GLOBAL",1)
Dead("TANALLY1")~`
instead. This is actually the negation of what Adalon's Blood mod introduces, so this should be fail safe.

**Comment by 11jo** [comment]
Yes it's better with one Global.

**Comment by Gitjas** [comment]
Fixed in v16!
